apiVersion: v1
kind: Service
metadata:
  name: students-delete-service
spec:
  selector:
    app: students-delete-service
  ports:
    - protocol: TCP
      port: 8085
      nodePort: 30085 
      targetPort: 8085
  type: NodePort 